apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgia-web
  namespace: crop-insurance
  labels:
    app: tgia-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tgia-web
  template:
    metadata:
      labels:
        app: tgia-web
    spec:
      containers:
      - name: tgia-web
        image: rome.thaicom.io/crop-insurance/tgia-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: rome

---

apiVersion: v1
kind: Service
metadata:
  name: tgia-web
  namespace: crop-insurance
spec:
  #type: NodePort
  selector:
    app: tgia-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
