import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import type { Metadata } from 'next'
import { Noto_Sans_Thai } from 'next/font/google'
import './globals.css'

const noto = Noto_Sans_Thai({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={noto.className}>
				<AppRouterCacheProvider options={{ enableCssLayer: true }}>
					<div className='flex h-full flex-1 flex-col'>{children}</div>
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
